TASK_ID = "easy"
DESCRIPTION = "Classification-only email triage for a busy operations inbox."


def get_task_data() -> list[dict]:
    return [
        {
            "id": "EZ-001",
            "subject": "Immediate wire needed for customs release",
            "body": "Pay this unofficial fee in crypto within 1 hour to release your shipment.",
            "sender": "customs-release@ship-fast-support.net",
            "timestamp": "2026-03-04T08:10:00",
            "classification": "spam",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-002",
            "subject": "Revised legal clause redlines",
            "body": "Please review attached redlines and reply by tomorrow noon.",
            "sender": "outside.counsel@lawfirm.com",
            "timestamp": "2026-03-04T08:25:00",
            "classification": "normal",
            "priority": "medium",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-003",
            "subject": "PagerDuty: payment API error budget exhausted",
            "body": "Checkout success rate dropped below SLA. Incident bridge is open now.",
            "sender": "alerts@pagerduty.com",
            "timestamp": "2026-03-04T08:42:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-004",
            "subject": "Q2 recruiting panel schedule",
            "body": "Please confirm your availability for candidate interviews this week.",
            "sender": "talent.ops@company.com",
            "timestamp": "2026-03-04T09:05:00",
            "classification": "normal",
            "priority": "medium",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-005",
            "subject": "Invoice correction needed now",
            "body": "Open attachment to avoid account termination and legal penalties.",
            "sender": "accounts-urgent@invoice-checks.biz",
            "timestamp": "2026-03-04T09:30:00",
            "classification": "spam",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-006",
            "subject": "Security: suspicious login from new location",
            "body": "Multiple admin attempts detected. Confirm containment actions within 30 minutes.",
            "sender": "soc@company.com",
            "timestamp": "2026-03-04T09:51:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-007",
            "subject": "Team offsite catering options",
            "body": "Please choose menu options before Friday.",
            "sender": "facilities@company.com",
            "timestamp": "2026-03-04T10:10:00",
            "classification": "normal",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-008",
            "subject": "Exclusive employee investment scheme",
            "body": "Guaranteed 18% weekly return. Send funds today to reserve your slot.",
            "sender": "vip-returns@assetgrowth.live",
            "timestamp": "2026-03-04T10:33:00",
            "classification": "spam",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-009",
            "subject": "Customer feedback digest",
            "body": "Weekly digest of customer NPS comments is ready for review.",
            "sender": "cx-analytics@company.com",
            "timestamp": "2026-03-04T10:55:00",
            "classification": "normal",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-010",
            "subject": "Urgent: payroll file rejected by bank",
            "body": "Bank rejected NACHA file. Correct and resend before 2 PM payroll cutoff.",
            "sender": "finance-ops@company.com",
            "timestamp": "2026-03-04T11:15:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-011",
            "subject": "Office parking policy update",
            "body": "Monthly permit process has changed. See handbook for details.",
            "sender": "people-ops@company.com",
            "timestamp": "2026-03-04T11:42:00",
            "classification": "normal",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "EZ-012",
            "subject": "Action required to maintain mailbox access",
            "body": "Validate credentials immediately or mailbox will be suspended.",
            "sender": "mail-admin@security-notice-mail.com",
            "timestamp": "2026-03-04T11:58:00",
            "classification": "spam",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
    ]
