TASK_ID = "hard"
DESCRIPTION = "Full triage with classification, priority assignment, and response drafting."


def get_task_data() -> list[dict]:
    return [
        {
            "id": "HD-001",
            "subject": "P1: Major customer unable to place orders",
            "body": "Acme Retail cannot complete checkout in production. Please provide ETA and mitigation plan.",
            "sender": "support.escalations@company.com",
            "timestamp": "2026-03-15T08:03:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": True,
            "required_response_keywords": ["eta", "mitigation", "incident"],
            "ideal_response": "Thanks for escalating. We have opened an incident, started mitigation, and will share ETA updates every 30 minutes.",
        },
        {
            "id": "HD-002",
            "subject": "Contract renewal questions",
            "body": "Can you confirm the updated billing terms and renewal date for our annual contract?",
            "sender": "procurement@northwind.com",
            "timestamp": "2026-03-15T08:20:00",
            "classification": "normal",
            "priority": "medium",
            "requires_response": True,
            "required_response_keywords": ["billing", "renewal", "confirm"],
            "ideal_response": "Thanks for your note. We confirm billing terms are updated and renewal remains on the agreed annual date.",
        },
        {
            "id": "HD-003",
            "subject": "Your mailbox storage is full",
            "body": "Click link and enter password to increase mailbox quota instantly.",
            "sender": "storage-admin@mail-upgrade-safe.net",
            "timestamp": "2026-03-15T08:41:00",
            "classification": "spam",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "HD-004",
            "subject": "Regulatory audit evidence request",
            "body": "Please send encryption and key rotation evidence by tomorrow morning.",
            "sender": "audit-team@regulator.gov",
            "timestamp": "2026-03-15T09:00:00",
            "classification": "normal",
            "priority": "high",
            "requires_response": True,
            "required_response_keywords": ["encryption", "rotation", "timeline"],
            "ideal_response": "We will provide encryption and key rotation evidence, with a complete packet delivered by tomorrow morning.",
        },
        {
            "id": "HD-005",
            "subject": "Urgent: chargeback spike from payment processor",
            "body": "Chargeback rate crossed threshold and could trigger account review. Need immediate owner response.",
            "sender": "risk@payments-partner.com",
            "timestamp": "2026-03-15T09:13:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": True,
            "required_response_keywords": ["owner", "investigation", "next steps"],
            "ideal_response": "Owner assigned. Investigation started and next steps will be shared as soon as root cause is confirmed.",
        },
        {
            "id": "HD-006",
            "subject": "Weekly hiring funnel summary",
            "body": "Sharing funnel metrics for this week. No action required unless you see anomalies.",
            "sender": "people-analytics@company.com",
            "timestamp": "2026-03-15T09:37:00",
            "classification": "normal",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "HD-007",
            "subject": "Security: exposed token detected in public repo",
            "body": "A production token appears in a public commit. Revoke and rotate immediately.",
            "sender": "security-response@company.com",
            "timestamp": "2026-03-15T09:58:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": True,
            "required_response_keywords": ["revoke", "rotate", "completed"],
            "ideal_response": "Acknowledged. We revoked the token, started key rotation, and will confirm completion once validated.",
        },
        {
            "id": "HD-008",
            "subject": "Office move FAQ",
            "body": "Updated FAQ for office move logistics next month.",
            "sender": "workplace@company.com",
            "timestamp": "2026-03-15T10:16:00",
            "classification": "normal",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "HD-009",
            "subject": "Last notice before tax seizure",
            "body": "Transfer payment within 30 minutes or assets will be seized.",
            "sender": "collections@tax-action-alert.com",
            "timestamp": "2026-03-15T10:34:00",
            "classification": "spam",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "HD-010",
            "subject": "Enterprise client asks for incident RCA",
            "body": "Please send preliminary root cause summary and customer-safe language today.",
            "sender": "account.director@company.com",
            "timestamp": "2026-03-15T10:57:00",
            "classification": "normal",
            "priority": "high",
            "requires_response": True,
            "required_response_keywords": ["root cause", "summary", "today"],
            "ideal_response": "Understood. We will send a preliminary root cause summary in customer-safe language later today.",
        },
        {
            "id": "HD-011",
            "subject": "P1: Data pipeline delay blocking invoicing",
            "body": "Invoicing jobs are stalled and finance cannot generate statements. Need immediate status update.",
            "sender": "billing-ops@company.com",
            "timestamp": "2026-03-15T11:18:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": True,
            "required_response_keywords": ["status", "workaround", "eta"],
            "ideal_response": "Status: incident active. Workaround is in progress and we will provide ETA after current mitigation check.",
        },
        {
            "id": "HD-012",
            "subject": "Request for product brochure",
            "body": "Could you share the latest product brochure PDF and pricing overview?",
            "sender": "prospect@contoso.com",
            "timestamp": "2026-03-15T11:44:00",
            "classification": "normal",
            "priority": "medium",
            "requires_response": True,
            "required_response_keywords": ["brochure", "pricing", "attached"],
            "ideal_response": "Thanks for reaching out. The latest brochure and pricing overview are attached for your review.",
        },
    ]
