TASK_ID = "medium"
DESCRIPTION = "Classification and prioritization triage with weighted urgency impact."


def get_task_data() -> list[dict]:
    return [
        {
            "id": "MD-001",
            "subject": "Re: Data Processing Agreement language",
            "body": "Need legal review comments by Thursday for vendor onboarding.",
            "sender": "procurement@company.com",
            "timestamp": "2026-03-10T08:05:00",
            "classification": "normal",
            "priority": "medium",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-002",
            "subject": "Critical: SOC2 evidence pack missing",
            "body": "Auditor requested control evidence in 90 minutes or finding will be issued.",
            "sender": "security-compliance@company.com",
            "timestamp": "2026-03-10T08:20:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-003",
            "subject": "Free conference pass claim",
            "body": "Claim all-inclusive pass by confirming corporate card details.",
            "sender": "events@free-pass-center.co",
            "timestamp": "2026-03-10T08:37:00",
            "classification": "spam",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-004",
            "subject": "Customer success handoff notes",
            "body": "Please review account handoff notes before tomorrow's kickoff.",
            "sender": "csm-east@company.com",
            "timestamp": "2026-03-10T09:00:00",
            "classification": "normal",
            "priority": "medium",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-005",
            "subject": "DLP alert: sensitive export attempt",
            "body": "Potential customer data export detected from unknown endpoint. Investigate now.",
            "sender": "siem@company.com",
            "timestamp": "2026-03-10T09:18:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-006",
            "subject": "New company swag catalog",
            "body": "Vote for Q3 swag items and submit preferences.",
            "sender": "brand@company.com",
            "timestamp": "2026-03-10T09:42:00",
            "classification": "normal",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-007",
            "subject": "Payment exception for strategic account",
            "body": "Client cannot process ACH today. Need alternate settlement instructions by noon.",
            "sender": "revops@company.com",
            "timestamp": "2026-03-10T10:03:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-008",
            "subject": "Firmware update recommendations",
            "body": "Routine recommendations for next maintenance window.",
            "sender": "it-platform@company.com",
            "timestamp": "2026-03-10T10:20:00",
            "classification": "normal",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-009",
            "subject": "RE: Earn crypto via invoice settlement",
            "body": "Switch payment destination wallet to receive settlement bonus.",
            "sender": "accounts@settlement-bonus.io",
            "timestamp": "2026-03-10T10:41:00",
            "classification": "spam",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-010",
            "subject": "Launch readiness checklist",
            "body": "Please complete your section of the release checklist by EOD.",
            "sender": "pm-release@company.com",
            "timestamp": "2026-03-10T11:06:00",
            "classification": "normal",
            "priority": "medium",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-011",
            "subject": "Incident: SSO login failures rising",
            "body": "Auth error rate crossed threshold. Need owner confirmation and mitigation plan.",
            "sender": "incident-commander@company.com",
            "timestamp": "2026-03-10T11:22:00",
            "classification": "urgent",
            "priority": "high",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
        {
            "id": "MD-012",
            "subject": "Cloud cost dashboard available",
            "body": "Monthly FinOps dashboard is published for review.",
            "sender": "finops@company.com",
            "timestamp": "2026-03-10T11:55:00",
            "classification": "normal",
            "priority": "low",
            "requires_response": False,
            "required_response_keywords": [],
            "ideal_response": None,
        },
    ]
